INSERT INTO employee (employee_id, first_name, last_name, email) VALUES
(1, 'Nat', 'Dufaire', 'ndufairer8@reference.com'),
(2, 'Talbert', 'Purrier', 'tpurrierr9@mtv.com'),
(3, 'Kalinda', 'Lavigne', 'klavignera@columbia.edu'),
(4, 'Trudey', 'Itzhaki', 'titzhakirb@hao123.com'),
(5, 'Loren', 'Weare', 'lwearerc@wikispaces.com'),
(6, 'Page', 'Holsey', 'pholseyrd@springer.com'),
(7, 'Kellen', 'Hellens', 'khellensre@spotify.com'),
(8, 'Reggy', 'Klossek', 'rklossekrf@taobao.com'),
(9, 'Shelia', 'De Ruel', 'sderuelrg@google.it'),
(10, 'Evered', 'Ovell', 'eovellrh@sohu.com'),
(11, 'Stefano', 'Ech', 'sechri@t-online.de'),
(12, 'Celisse', 'Mickleborough', 'cmickleboroughrj@t-online.de'),
(13, 'Norma', 'Arminger', 'narmingerrk@delicious.com'),
(14, 'Vasili', 'Jime', 'vjimerl@bbb.org'),
(15, 'Delphine', 'Sergent', 'dsergentrm@jugem.jp'),
(16, 'Byron', 'Mayor', 'bmayorrn@netscape.com'),
(17, 'Janean', 'Coatsworth', 'jcoatsworthro@purevolume.com'),
(18, 'Georgeanna', 'Garman', 'ggarmanrp@surveymonkey.com'),
(19, 'Ardeen', 'Caret', 'acaretrq@wsj.com'),
(20, 'Delora', 'Bigglestone', 'dbigglestonerr@usatoday.com');